### ISSUE TITLE
six-zero rule might not work at the very beginning?

### ISSUE THREAD

**Issue by domino14** [domino14/macondo#118]
``` I found a self-play game both using noleave where they each had CDDPRRV and BDFGHNQ to start and passed back and forth 199557414 times```

**Comment by ddugovic** [comment]
It appears PASS is always valid. :-)
https://github.com/domino14/macondo/blob/57f213b3c36152fcf9a44454732ade1d38ceaea2/game/game.go#L288-L290

**Comment by domino14** [comment]
This was caused by reuse of a game object and not resetting `scorelessTurns` to 0 at the beginning.
