### ISSUE TITLE
endgame analyzer not ending game!?

### ISSUE THREAD

**Issue by domino14** [domino14/macondo#119]
regression?

`> load woogles SBRtWRzo`

`> turn 21`

`> endgame 6`

After a few minutes it prints out:

```{"level":"info","time":"2021-01-29T18:13:35-05:00","message":"Best seq so far is [<0x140003f5ea0 action: play word: L1 JET. score: 21 tp: 3 leave: ILMS equity: 0.000 valu: 17.000> <0x14000fb2280 action: play word: E9 .AE score: 20 tp: 2 leave: IOORT equity: 0.000 valu: 11.000> <0x140030ea1e0 action: play word: 15L MIL. score: 16 tp: 3 leave: S equity: 0.000 valu: 5.000> <0x14004e46fa0 action: play word: C3 ROTI score: 14 tp: 4 leave: O equity: 0.000 valu: 0.000> <0x1401dc5ac80 action: play word: 11J S.. score: 12 tp: 1 leave:  equity: 0.000 valu: 14.000> <0x140af2ada40 action: play word: 13F .O. score: 10 tp: 1 leave:  equity: 0.000 valu: 10.000>]"}```

game should have been ended with penultimate move (no leave) so why did it generate an extra move?

**Comment by domino14** [comment]
endgame 4 shows  it faster

**Comment by domino14** [comment]
`2df21b1f167bb45a4d129a965f16d6846f951eac is the first bad commit`

**Comment by martindemello** [comment]
surprising github doesn't autolink that!

**Comment by martindemello** [comment]
https://github.com/domino14/macondo/commit/2df21b1f167bb45a4d129a965f16d6846f951eac
