### ISSUE TITLE
bot passes with FFGKMVW

### ISSUE THREAD

**Issue by domino14** [domino14/macondo#196]
all exchanges get evaluated negatively with this rack, and thus macondo evaluates pass above them (which is evaluated as a 0). pass should be evaluated as the average of all 6-tile leaves or something of the sort (Quackle uses -1000 as a shortcut which isn't a bad idea)

**Comment by martindemello** [comment]
why do all exchanges get evaluated negatively? that seems like a deeper issue; surely x7 should score above pass (also the leave evaluator should ideally be extended to handle 7-tile leaves if it isn't already, rather than hacking it as the average of all 6-tile leaves)

**Comment by domino14** [comment]
7-tile leaves are so rare that it doesn’t seem worth to add that many more
leaves (it would probably at least double the size of the hash).

Exchange 7 is a 0-tile leave, which we evaluate as zero - not sure what is
a better static value for it. The problem is that pass is also zero so I
bet sometimes it gets picked.

**Comment by martindemello** [comment]
ah right, i meant to say `x7` should score above `pass` because the leave of `pass` is highly negative and the leave of `x7` is 0.
