### ISSUE TITLE
montecarlo sim should use old method of picking random tiles

### ISSUE THREAD

**Issue by domino14** [domino14/macondo#207]
For the sim to be most accurate (exhibit the least "noise") for every iteration both us and the opponent should draw the same tiles from the bag for each play being considered in that iteration. 

We should shuffle the bag after every iteration and establish its order as the drawing order, instead of the approach we currently use. One idea would be to just make a new bag type to be used only for sims that can do this.

**Comment by ddugovic** [comment]
Interesting, yeah I suppose you'd want both players to draw equally lucky racks (or have some way of modeling noise based upon luck and subtracting "spread improvement versus expected improvement from luck").

**Comment by ddugovic** [comment]
Alternatively, perhaps sim should do two iterations... after drawing order is established, then:
* Iteration 1: first player draws from the beginning of the queue and second player draws from the end of the queue until the end of the game
* Iteration 2: first player draws from the end of the queue and second player draws from the beginning of the queue until the end of the game
