### ISSUE TITLE
investigate why KUBIE has a non 100% win when simming 2 ply

### ISSUE THREAD

**Issue by domino14** [domino14/macondo#215]
https://www.cross-tables.com/annotated.php?u=39683#23#

**Comment by ddugovic** [comment]
I'd test this with #148 but both in that branch and on `master` the game doesn't load with `load xt 39683` (or I'm not doing it right).

**Comment by domino14** [comment]
i think this particular issue is not actually an issue, i think it's
because a lot of the times the game doesn't end and it's applying
statistics. the correct solution before I get pre-endgames working is to do
a many-ply sim, but this crashes at the moment. (see comment in #214)
