### ISSUE TITLE
Library usage

### ISSUE THREAD

**Issue by brianfromoregon** [domino14/macondo#286]
Hi
I was hoping for a pointer or example to use macando as a library, specifically I want to send it the current scrabble board plus a rack, and have it think for up to N seconds before advising the best plays. 
Hope you don’t mind my using the issues area to ask this, I wasn’t sure of any other forum/discord suitable for questions.
Thanks!

**Comment by domino14** [comment]
Hiya, we have a multi-purpose Discord for Woogles (https://github.com/domino14/liwords) and related technology. Discord invite is here:

https://discord.gg/GqkUqA7ENm

To answer your question, the best way I can think of doing this right now is to use the CGP format for the position:

https://github.com/domino14/macondo/blob/master/cgp/README.md

Then take a look at this code:

https://github.com/domino14/macondo/blob/master/cmd/lambda/main.go

This is self-contained code for running Macondo as a lambda function. The `Handle` function above should help in how to parse the CGP and create a bot that thinks for up to X seconds before returning a valid play. 

I'll close this issue for now but please feel free to join our Discord's `#tech-general` channel if you have more questions.
