### ISSUE TITLE
add some getting started instructions

### ISSUE THREAD

**Issue by martindemello** [domino14/macondo#54]
```
$ ./main 
{"level":"info","time":"2020-05-30T17:06:22-07:00","message":"Terminal color support is on."}
{"level":"info","time":"2020-05-30T17:06:22-07:00","message":"Loaded config: &{false ./data/strategy ./data/lexica NWL18 English}"}
{"level":"info","path":"/home/mdemello/github/macondo/data/lexica","time":"2020-05-30T17:06:22-07:00","message":"new lexicon path"}
{"level":"info","sppath":"/home/mdemello/github/macondo/data/strategy","time":"2020-05-30T17:06:22-07:00","message":"new strat params path"}
macondo> new
Error: open /home/mdemello/github/macondo/data/lexica/gaddag/NWL18.gaddag: no such file or directory
macondo> exit
{"level":"info","time":"2020-05-30T17:06:34-07:00","message":"got quit signal..."}
{"level":"info","time":"2020-05-30T17:06:34-07:00","message":"server gracefully shutting down"}
```

**Comment by domino14** [comment]
Hey Martin, thanks for the issue - you’re right that I need a few more details. If you look at domino14.github.io/macondo, there are instructions there on building a gaddag with the make_gaddag executable.

Additionally, you can download the darwin release tarball, which comes with the NWL18 and CSW19 gaddags. Please let me know if this doesn’t work for you.

**Comment by martindemello** [comment]
i do not know enough go to figure out the invocation to make `make_gaddag`. i suggest you have a makefile that runs the right commands to build all the executables.

(on linux, so the darwin binaries won't help)

**Comment by martindemello** [comment]
nevermind, figured it out (i was expecting it to write the binary to the same place as main.go). i'll send in a PR with a Makefile.
