### ISSUE TITLE
Shell in Unix: db2 database with data with umlaut not exported  to CSV

### ISSUE THREAD

**Issue by WatermeYue** [domino14/macondo#62]
Hi, I have written a .sh file and in this .sh file I have selected some data which exports a .csv file. 
I recognized that all the lines with umlaut (ä,ö,ü etc.) are not considered to be exported, and the rest of the data are okay. So I think it might be a problem of data format in shell code.
I used "UTF-8" to encode the .sh file.
And my db2 code is something like this:
`SELECT * FROM table 
WHERE something IN ('aktiviert', 'gekündigt','beendet')`
I suppose there is something wrong with "gekündigt". Could someone help? 
Many thanks!

**Comment by domino14** [comment]
Hi, I am confused. What does this have to do with Macondo?

**Comment by WatermeYue** [comment]
ah sorrry, i think i put it in the wrong stream... I will close it
