### ISSUE TITLE
shell has trouble with some GCG games

### ISSUE THREAD

**Issue by domino14** [domino14/macondo#75]
`macondo> load gcgio/testdata/josh2.gcg`

then 

`macondo> turn 21` 

then type in `n` and it screws up. Yet the tests for this GCG pass.

**Comment by ddugovic** [comment]
Changing turn 21 in the GCG to play `B3 VS` for 5 points then challenging off `VS` does not produce this error.  This error seems to only occur when challenged-off tiles do not appear multiple times in the bag (in this case, on move 21 the bag contains 2 V tiles).

**Comment by ddugovic** [comment]
Here is the faulty assumption (that in the event of a successful challenge, the opponent's rack should be set to `rack`):

https://github.com/domino14/macondo/blob/27627dd2340d43e0b76c773b91b51654b0b12369/game/game.go#L741-L747

**Comment by domino14** [comment]
thanks, this was fixed
